### ISSUE TITLE
Peer to peer code review

### ISSUE THREAD

**Issue by Ruthmy** [LarryIVC/EventPage#1]
Hey Larry! 👋 
As you know today we had our peer to peer code review session, so here are our comments:

**Ruth:**
- Your site looks great Larry, visually you follow the styles of the assigned template very well. My only observation for you is about the URL's of the images, as some of them are not displayed correctly. When you call them from places like the index you don't need to put a `/` at the beginning, so instead of `/images/myimage.png` you put `images/myimage.png`

That's it. Thanks for sharing your work with us, Larry 🤝

**Comment by DamianDib9** [comment]
### **Hi Larry!**

Your project looks really good! Just a friendly reminder that, as you are supposed the figma template, I kindly suggest you to make an adjustment on the navbar. It should not be white with that drop shadow effect:
And that's all, keep on that track buddy!

**Happy coding  😎👍**

**Comment by LarryIVC** [comment]
@DamianDib9, @Ruthmy:
Thank you for your suggestions and I applied them to my project
Happy Coding
